# Development override for docker-compose
# This file is automatically loaded by docker-compose in development

version: '3.8'

services:
  gateway:
    # For development, mount source code for live reload
    volumes:
      - .:/app
      - ./bigquery:/app/credentials:ro
      - ./logs:/app/logs
      # Exclude vendor and build directories
      - /app/vendor
      - /app/bin
    environment:
      ENV: development
      # More verbose logging in development
      LOG_LEVEL: debug
    # Rebuild on code changes (requires docker-compose up --build)
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Or use go run for live reload (uncomment below, comment build above)
    # command: go run cmd/server/main_chi.go
    # working_dir: /app

  # In development, don't persist Redis data
  redis:
    volumes: []

  # Disable monitoring in development (comment out if you want it)
  prometheus:
    profiles:
      - monitoring

  grafana:
    profiles:
      - monitoring