apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: prod

images:
- name: asia-southeast2-docker.pkg.dev/luminous-lodge-376415/jenkins/inaproc-apigateway-docs
  newTag: latest
