apiVersion: v1
kind: Service
metadata:
  name: inaproc-api-gateway-docs
  namespace: prod
spec:
  selector:
    app: inaproc-api-gateway-docs
  ports:
  - name: inaproc-api-gateway-docs
    port: 3000