apiVersion: apps/v1
kind: Deployment
metadata:
  name: inaproc-api-gateway
  namespace: prod
  labels:
    app: inaproc-api-gateway
    component: api-gateway
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inaproc-api-gateway
  template:
    metadata:
      labels:
        app: inaproc-api-gateway
        component: api-gateway
        environment: production
    spec:
      containers:
      - name: inaproc-api-gateway
        image: asia-southeast2-docker.pkg.dev/luminous-lodge-376415/jenkins/inaproc-api-gateway:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: FUSIO_ENV
          value: "prod"
        - name: FUSIO_DEBUG
          value: "false"
        - name: FUSIO_PROJECT_KEY
          value: "cee262a5a1bdd205cbfe0dfc2ad4eddf"
        - name: FUSIO_CONNECTION
          valueFrom:
            secretKeyRef:
              name: gateway-service-secrets
              key: GATEWAY_POSTGRES_URI
        - name: FUSIO_MAILER
          value: "native://default"
        - name: FUSIO_MESSENGER
          value: "doctrine://default"
        - name: FUSIO_URL
          value: "https://data.eproc.dev"
        - name: FUSIO_APPS_URL
          value: "https://data.eproc.dev/apps"
        - name: FUSIO_BACKEND_USER
          value: "admin"
        - name: FUSIO_BACKEND_EMAIL
          value: "admin@fusio-project.org"
        - name: FUSIO_BACKEND_PW
          valueFrom:
            secretKeyRef:
              name: gateway-service-secrets
              key: GATEWAY_SERVICE_FUSIO_BACKEND_PW
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /apps/account
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /apps/account
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3