apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-postgres-uri
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: gateway-postgres-uri
    creationPolicy: Owner
  data:
  - secretKey: GATEWAY_POSTGRES_URI
    remoteRef:
      key: GATEWAY_POSTGRES_URI
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-service-secrets
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: gateway-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: GATEWAY_SERVICE_POSTGRES_DATABASE
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_DATABASE
  - secretKey: GATEWAY_SERVICE_POSTGRES_HOST
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_HOST
  - secretKey: GATEWAY_SERVICE_POSTGRES_PASSWORD
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_PASSWORD
  - secretKey: GATEWAY_SERVICE_POSTGRES_PORT
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_PORT
  - secretKey: GATEWAY_SERVICE_POSTGRES_USER
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_USER
  - secretKey: GATEWAY_SERVICE_REDIS_HOST
    remoteRef:
      key: GATEWAY_SERVICE_REDIS_HOST
  - secretKey: GATEWAY_SERVICE_REDIS_PASSWORD
    remoteRef:
      key: GATEWAY_SERVICE_REDIS_PASSWORD
  - secretKey: GATEWAY_SERVICE_FUSIO_BACKEND_PW
    remoteRef:
      key: GATEWAY_SERVICE_FUSIO_BACKEND_PW
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-workflow-secrets
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: gateway-workflow-secrets
    creationPolicy: Owner
  data:
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_DATABASE
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_DATABASE
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_HOST
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_PORT
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_PORT
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_USER
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_USER
  - secretKey: GATEWAY_WORKFLOW_REDIS_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_REDIS_HOST
  - secretKey: GATEWAY_WORKFLOW_REDIS_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_REDIS_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_SMPT_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_HOST
  - secretKey: GATEWAY_WORKFLOW_SMPT_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_SMPT_SENDER
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_SENDER
  - secretKey: GATEWAY_WORKFLOW_SMPT_USER
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_USER