apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secrets.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: prod

commonLabels:
  app.kubernetes.io/name: inaproc-api-gateway
  app.kubernetes.io/part-of: inaproc-apigateway

images:
- name: asia-southeast2-docker.pkg.dev/luminous-lodge-376415/jenkins/inaproc-api-gateway
  newTag: latest

namespace: prod