apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-gateway-service-secrets
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: data-gateway-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_HOST
    remoteRef:
      key: GATEWAY_SERVICE_REDIS_HOST
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: GATEWAY_SERVICE_REDIS_PASSWORD
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_HOST
  - secretKey: POSTGRES_PORT
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_PORT
  - secretKey: POSTGRES_DATABASE
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_DATABASE
  - secretKey: POSTGRES_USER
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: GATEWAY_SERVICE_POSTGRES_PASSWORD
  - secretKey: DREMIO_HOST
    remoteRef:
      key: GATEWAY_SERVICE_DREMIO_HOST
  - secretKey: DREMIO_USERNAME
    remoteRef:
      key: GATEWAY_SERVICE_DREMIO_USERNAME
  - secretKey: DREMIO_PASSWORD
    remoteRef:
      key: GATEWAY_SERVICE_DREMIO_PASSWORD
  - secretKey: BIGQUERY_PROJECT_ID
    remoteRef:
      key: GATEWAY_SERVICE_BIGQUERY_PROJECT_ID
  - secretKey: GOOGLE_APPLICATION_CREDENTIALS
    remoteRef:
      key: GATEWAY_SERVICE_GOOGLE_APPLICATION_CREDENTIALS