apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: data-gateway-service@gtp-apigateway-prod.iam.gserviceaccount.com
  name: data-gateway-service
  namespace: prod
  labels:
    app: data-gateway-service
    component: data-gateway
    environment: production
