name = "docs-fuma-manual"
compatibility_date = "2024-09-04"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages --experimental-minify"
cwd = ""

[env.preview.vars]
NODE_ENV = "development"

[env.production.vars]
NODE_ENV = "production"
