apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workflow-n8n-secrets
  namespace: prod
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: workflow-n8n-secrets
    creationPolicy: Owner
  data:
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_DATABASE
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_DATABASE
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_HOST
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_PORT
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_PORT
  - secretKey: GATEWAY_WORKFLOW_POSTGRES_USER
    remoteRef:
      key: GATEWAY_WORKFLOW_POSTGRES_USER
  - secretKey: GATEWAY_WORKFLOW_REDIS_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_REDIS_HOST
  - secretKey: GATEWAY_WORKFLOW_REDIS_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_REDIS_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_SMPT_HOST
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_HOST
  - secretKey: GATEWAY_WORKFLOW_SMPT_PASSWORD
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_PASSWORD
  - secretKey: GATEWAY_WORKFLOW_SMPT_SENDER
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_SENDER
  - secretKey: GATEWAY_WORKFLOW_SMPT_USER
    remoteRef:
      key: GATEWAY_WORKFLOW_SMPT_USER